#feature set 2
ask_range = AAPL.ASK_PRICE10 - AAPL.ASK_PRICE1
bid_range = AAPL.BID_PRICE1 - AAPL.BID_PRICE10

ask21 =np.absolute(AAPL.ASK_PRICE2 - AAPL.ASK_PRICE1)
ask32 =np.absolute(AAPL.ASK_PRICE3 - AAPL.ASK_PRICE2)
ask43 =np.absolute(AAPL.ASK_PRICE4 - AAPL.ASK_PRICE3)
ask54 =np.absolute(AAPL.ASK_PRICE5 - AAPL.ASK_PRICE4)
ask65 =np.absolute(AAPL.ASK_PRICE6 - AAPL.ASK_PRICE5)
ask76 =np.absolute(AAPL.ASK_PRICE7 - AAPL.ASK_PRICE6)
ask87 =np.absolute(AAPL.ASK_PRICE8 - AAPL.ASK_PRICE7)
ask98 =np.absolute(AAPL.ASK_PRICE9 - AAPL.ASK_PRICE8)
ask109 =np.absolute(AAPL.ASK_PRICE10 - AAPL.ASK_PRICE9)

BID21=np.absolute(AAPL.BID_PRICE2 - AAPL.BID_PRICE1)
BID32 =np.absolute(AAPL.BID_PRICE3 - AAPL.BID_PRICE2)
BID43 =np.absolute(AAPL.BID_PRICE4 - AAPL.BID_PRICE3)
BID54 =np.absolute(AAPL.BID_PRICE5 - AAPL.BID_PRICE4)
BID65 =np.absolute(AAPL.BID_PRICE6 - AAPL.BID_PRICE5)
BID76 =np.absolute(AAPL.BID_PRICE7 - AAPL.BID_PRICE6)
BID87 =np.absolute(AAPL.BID_PRICE8 - AAPL.BID_PRICE7)
BID98 =np.absolute(AAPL.BID_PRICE9 - AAPL.BID_PRICE8)
BID109 =np.absolute(AAPL.BID_PRICE10 - AAPL.BID_PRICE9)

v_ask_bid = np.sum((AAPL.ASK_SIZE1 - AAPL.BID_SIZE1,AAPL.ASK_SIZE2 - AAPL.BID_SIZE2,
                    AAPL.ASK_SIZE3 - AAPL.BID_SIZE3,AAPL.ASK_SIZE4 - AAPL.BID_SIZE4,
                    AAPL.ASK_SIZE5 - AAPL.BID_SIZE5,AAPL.ASK_SIZE6 - AAPL.BID_SIZE6,
                    AAPL.ASK_SIZE7 - AAPL.BID_SIZE7,AAPL.ASK_SIZE8 - AAPL.BID_SIZE8,
                    AAPL.ASK_SIZE9 - AAPL.BID_SIZE9,AAPL.ASK_SIZE10 - AAPL.BID_SIZE10)
)